'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { api } from '@/lib/api';
import { LEGAL_VERSIONS, LEGAL_EFFECTIVE_DATE } from '@/lib/legal-versions';

/* ─── Shield SVG monogram ─── */
function ShieldLogo() {
  return (
    <svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M20 2L4 10v10c0 11 7 18 16 20 9-2 16-9 16-20V10L20 2z" fill="#c2fa69" fillOpacity="0.12" stroke="#c2fa69" strokeWidth="1.5" />
      <text x="20" y="26" textAnchor="middle" fill="#c2fa69" fontFamily="monospace" fontSize="16" fontWeight="700">S</text>
    </svg>
  );
}

/* ─── Terms of Service Content ─── */
function TermsContent() {
  return (
    <div className="prose prose-invert prose-sm max-w-none" style={{ color: '#d1d5db' }}>
      <h3 className="text-white">1. Acceptance of Terms</h3>
      <p>By accessing or using AI Sentinels (&quot;the Platform&quot;), operated by Strivana.com LLC (&quot;the Company&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree, do not use the Platform.</p>

      <h3 className="text-white">2. Description of Service</h3>
      <p>AI Sentinels is a multi-tenant Integrated Management System (IMS) SaaS platform for ISO 9001, ISO 14001, and ISO 45001 compliance management, powered by AI Sentinels (autonomous agents).</p>

      <h3 className="text-white">3. Eligibility</h3>
      <p>You must be at least 18 years old and have the authority to bind your organization to these Terms. By using the Platform, you represent that you meet these requirements.</p>

      <h3 className="text-white">4. Account Registration</h3>
      <p>4.1. You must provide accurate and complete information during registration.</p>
      <p>4.2. You are responsible for maintaining the security of your account credentials, including MFA configuration.</p>
      <p>4.3. You must notify us immediately of any unauthorized access to your account.</p>

      <h3 className="text-white">5. Multi-Tenant Architecture</h3>
      <p>5.1. Each organization (&quot;Tenant&quot;) receives an isolated data environment with row-level security.</p>
      <p>5.2. You may not attempt to access data belonging to other Tenants.</p>
      <p>5.3. Tenant administrators are responsible for managing user access within their organization.</p>

      <h3 className="text-white">6. AI Sentinels and Automated Processing</h3>
      <p>6.1. The Platform employs AI agents (&quot;Sentinels&quot;) including Qualy, Envi, Saffy, Doki, Audie, Nexus, Omni, and Ghost to assist with compliance management.</p>
      <p>6.2. AI-generated content (documents, audit findings, CAPA recommendations, risk assessments) is provided as guidance only and does not constitute professional certification or legal advice.</p>
      <p>6.3. You are solely responsible for reviewing, approving, and implementing any AI-generated recommendations.</p>
      <p>6.4. <strong>THE PLATFORM DOES NOT GUARANTEE ISO CERTIFICATION. AI SENTINELS ARE TOOLS TO ASSIST YOUR COMPLIANCE EFFORTS, NOT REPLACEMENTS FOR QUALIFIED MANAGEMENT SYSTEM PROFESSIONALS OR CERTIFICATION BODY AUDITORS.</strong></p>

      <h3 className="text-white">7. Subscription Plans and Billing</h3>
      <p>7.1. The Platform offers Starter, Professional, and Enterprise subscription tiers.</p>
      <p>7.2. AI credit usage is metered and limited per plan tier.</p>
      <p>7.3. Payment is processed through Wise Business API. All fees are quoted in USD.</p>
      <p>7.4. Subscriptions renew automatically unless cancelled before the renewal date.</p>

      <h3 className="text-white">8. Data Ownership and Retention</h3>
      <p>8.1. You retain ownership of all data you upload to the Platform.</p>
      <p>8.2. Compliance evidence stored in the Records Vault is retained with Object Lock (COMPLIANCE mode, 7-year retention) as required by ISO standards.</p>
      <p>8.3. Upon account termination, your data will be retained for the legally required retention period, after which it will be securely deleted.</p>
      <p>8.4. Export functionality is available to download your data at any time.</p>

      <h3 className="text-white">9. Acceptable Use</h3>
      <p>You agree not to: (a) reverse engineer, decompile, or disassemble the Platform; (b) use the Platform for any unlawful purpose; (c) attempt to circumvent security controls, RLS policies, or access controls; (d) upload malicious content or attempt to compromise the AI Sentinels; (e) resell or redistribute access to the Platform without authorization.</p>

      <h3 className="text-white">10. Intellectual Property</h3>
      <p>10.1. The Platform, including its AI models, Sentinel personas, and interface design, is the intellectual property of Strivana.com LLC.</p>
      <p>10.2. Blog content generated by Ghost Sentinel is owned by Strivana.com LLC.</p>
      <p>10.3. <strong>YOU MAY NOT USE AI SENTINELS OUTPUT TO TRAIN COMPETING AI MODELS OR SERVICES.</strong></p>

      <h3 className="text-white">11. Limitation of Liability</h3>
      <p>11.1. <strong>THE PLATFORM IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.</strong></p>
      <p>11.2. <strong>IN NO EVENT SHALL STRIVANA.COM LLC BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE PLATFORM, INCLUDING BUT NOT LIMITED TO FAILED AUDITS, LOST CERTIFICATIONS, REGULATORY PENALTIES, OR BUSINESS LOSSES.</strong></p>
      <p>11.3. Our total liability shall not exceed the amount you paid for the Platform in the 12 months preceding the claim.</p>

      <h3 className="text-white">12. Indemnification</h3>
      <p>You agree to indemnify and hold harmless Strivana.com LLC from any claims, damages, or expenses arising from your use of the Platform or violation of these Terms.</p>

      <h3 className="text-white">13. Security and Compliance</h3>
      <p>13.1. The Platform implements encryption at rest (KMS) and in transit (TLS 1.2+).</p>
      <p>13.2. All actions are logged in an immutable audit trail (DynamoDB, 7-year retention).</p>
      <p>13.3. Multi-factor authentication (MFA) is available and recommended for all users.</p>
      <p>13.4. We maintain AWS GuardDuty, Security Hub, and CloudTrail monitoring.</p>

      <h3 className="text-white">14. Service Availability</h3>
      <p>14.1. We target 99.9% uptime but do not guarantee uninterrupted service.</p>
      <p>14.2. Scheduled maintenance will be communicated in advance.</p>
      <p>14.3. We are not liable for downtime caused by AWS infrastructure issues, force majeure, or your internet connectivity.</p>

      <h3 className="text-white">15. Modifications to Terms</h3>
      <p>We may update these Terms at any time. Material changes will be communicated via email and in-platform notification. Continued use after notification constitutes acceptance of updated Terms.</p>

      <h3 className="text-white">16. Termination</h3>
      <p>16.1. You may terminate your account at any time through Settings.</p>
      <p>16.2. We may suspend or terminate accounts for Terms violations.</p>
      <p>16.3. Upon termination, your access ceases immediately. Data retention per Section 8 applies.</p>

      <h3 className="text-white">17. Governing Law</h3>
      <p>These Terms are governed by the laws of the State of Florida, United States. Any disputes shall be resolved in the courts of Miami-Dade County, Florida.</p>

      <h3 className="text-white">18. Contact</h3>
      <p>For questions about these Terms, contact: legal@aisentinels.io</p>
      <p>Strivana.com LLC<br />Miami, Florida, United States</p>
    </div>
  );
}

/* ─── Privacy Policy Content ─── */
function PrivacyContent() {
  return (
    <div className="prose prose-invert prose-sm max-w-none" style={{ color: '#d1d5db' }}>
      <h3 className="text-white">1. Introduction</h3>
      <p>This Privacy Policy describes how Strivana.com LLC (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;) collects, uses, stores, and protects your information when you use AI Sentinels (&quot;the Platform&quot;).</p>

      <h3 className="text-white">2. Information We Collect</h3>
      <p>2.1. <strong>Account Information:</strong> Name, email address, organization name, and role when you register.</p>
      <p>2.2. <strong>Usage Data:</strong> Actions performed on the Platform, AI Sentinel interactions, documents created, audits conducted, and compliance activities.</p>
      <p>2.3. <strong>Technical Data:</strong> IP address, browser type, device information, and access timestamps (logged in immutable audit trail).</p>
      <p>2.4. <strong>Compliance Data:</strong> Documents, audit records, CAPA items, risk assessments, and management review data you upload or generate.</p>
      <p>2.5. <strong>AI Interaction Data:</strong> Prompts sent to and responses received from AI Sentinels, including token usage metrics.</p>

      <h3 className="text-white">3. How We Use Your Information</h3>
      <p>3.1. To provide, maintain, and improve the Platform and its AI capabilities.</p>
      <p>3.2. To process your compliance management activities.</p>
      <p>3.3. To generate audit trails as required by ISO standards.</p>
      <p>3.4. To send transactional emails (approvals, alerts, reports).</p>
      <p>3.5. To detect and prevent unauthorized access or security threats.</p>
      <p>3.6. To aggregate anonymized usage analytics for Platform improvement.</p>

      <h3 className="text-white">4. Data Storage and Security</h3>
      <p>4.1. All data is stored in AWS us-east-1 (Virginia) with replication to eu-west-1 (Ireland) for compliance evidence.</p>
      <p>4.2. Data is encrypted at rest using AWS KMS (AES-256) and in transit using TLS 1.2+.</p>
      <p>4.3. Compliance evidence is stored with S3 Object Lock (COMPLIANCE mode, 7-year retention).</p>
      <p>4.4. Database access uses IAM authentication and row-level security (RLS) for tenant isolation.</p>
      <p>4.5. Access is monitored via AWS CloudTrail, GuardDuty, and Security Hub.</p>

      <h3 className="text-white">5. Data Sharing</h3>
      <p>5.1. We do not sell your personal data.</p>
      <p>5.2. We share data only with: (a) AWS infrastructure services (hosting, storage, compute); (b) Anthropic/Google for AI processing (prompts are not used to train models); (c) Law enforcement when required by legal process.</p>
      <p>5.3. Your compliance data is never shared with other Tenants.</p>

      <h3 className="text-white">6. AI Processing</h3>
      <p>6.1. AI Sentinels process your data to provide compliance assistance.</p>
      <p>6.2. AI interactions are logged for audit purposes and quality improvement.</p>
      <p>6.3. We do not use your data to train third-party AI models.</p>
      <p>6.4. AI-generated content may be reviewed for quality assurance.</p>

      <h3 className="text-white">7. Data Retention</h3>
      <p>7.1. Active account data: retained while your account is active.</p>
      <p>7.2. Compliance evidence: 7-year minimum retention (ISO requirement).</p>
      <p>7.3. Audit trail logs: 7-year retention (immutable, DynamoDB).</p>
      <p>7.4. Blog content: retained indefinitely (public).</p>
      <p>7.5. Deleted data: securely purged after retention period expires.</p>

      <h3 className="text-white">8. Your Rights</h3>
      <p>8.1. <strong>Access:</strong> You may export your data at any time through the Platform.</p>
      <p>8.2. <strong>Correction:</strong> You may update your account information in Settings.</p>
      <p>8.3. <strong>Deletion:</strong> You may request account deletion (subject to retention requirements).</p>
      <p>8.4. <strong>Portability:</strong> You may export compliance data in standard formats.</p>
      <p>8.5. To exercise these rights, contact: privacy@aisentinels.io</p>

      <h3 className="text-white">9. Cookies and Tracking</h3>
      <p>9.1. We use essential cookies for authentication and session management.</p>
      <p>9.2. We do not use third-party advertising cookies.</p>
      <p>9.3. Analytics data is collected in aggregate and anonymized.</p>

      <h3 className="text-white">10. Changes to This Policy</h3>
      <p>We may update this Privacy Policy. Material changes will be communicated via email and require re-acceptance through the Platform.</p>

      <h3 className="text-white">11. Contact</h3>
      <p>For privacy inquiries: privacy@aisentinels.io</p>
      <p>Data Protection Contact: legal@aisentinels.io</p>
      <p>Strivana.com LLC<br />Miami, Florida, United States</p>
    </div>
  );
}

/* ─── Page ─── */
export default function LegalOnboardingPage() {
  const router = useRouter();
  const [termsAccepted, setTermsAccepted] = useState(false);
  const [privacyAccepted, setPrivacyAccepted] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const canProceed = termsAccepted && privacyAccepted;

  const handleAccept = async () => {
    setLoading(true);
    setError(null);
    try {
      await Promise.all([
        api.post('/api/v1/legal/accept', {
          documentType: 'terms',
          version: LEGAL_VERSIONS.terms,
        }),
        api.post('/api/v1/legal/accept', {
          documentType: 'privacy',
          version: LEGAL_VERSIONS.privacy,
        }),
      ]);
      router.push('/dashboard');
    } catch {
      setError('Failed to record acceptance. Please try again.');
      setLoading(false);
    }
  };

  return (
    <div
      className="min-h-screen flex items-center justify-center px-4 py-12"
      style={{ background: '#0a0a0a' }}
    >
      <div
        className="w-full max-w-2xl rounded-xl p-8"
        style={{ background: '#111111', border: '1px solid rgba(255,255,255,0.08)' }}
      >
        {/* Header */}
        <div className="flex items-center gap-3 mb-2">
          <ShieldLogo />
          <span className="text-white font-semibold text-lg">AI Sentinels</span>
        </div>
        <h1 className="text-xl font-bold text-white mt-4">Before you continue</h1>
        <p className="text-sm mt-1" style={{ color: '#9ca3af' }}>
          Please review and accept our Terms of Service and Privacy Policy to access the platform.
        </p>

        <div className="mt-6 space-y-6">
          {/* Terms Section */}
          <div>
            <h2 className="text-sm font-semibold text-white mb-2">
              Terms of Service &mdash; Version {LEGAL_VERSIONS.terms}
            </h2>
            <div
              className="max-h-64 overflow-y-auto rounded-lg p-4 text-xs leading-relaxed"
              style={{ background: '#0a0a0a', border: '1px solid rgba(255,255,255,0.06)' }}
            >
              <TermsContent />
            </div>
          </div>

          {/* Privacy Section */}
          <div>
            <h2 className="text-sm font-semibold text-white mb-2">
              Privacy Policy &mdash; Version {LEGAL_VERSIONS.privacy}
            </h2>
            <div
              className="max-h-64 overflow-y-auto rounded-lg p-4 text-xs leading-relaxed"
              style={{ background: '#0a0a0a', border: '1px solid rgba(255,255,255,0.06)' }}
            >
              <PrivacyContent />
            </div>
          </div>

          {/* Checkboxes */}
          <div className="space-y-3">
            <label className="flex items-start gap-3 cursor-pointer group">
              <input
                type="checkbox"
                checked={termsAccepted}
                onChange={(e) => setTermsAccepted(e.target.checked)}
                className="mt-0.5 h-4 w-4 rounded border-white/20 bg-transparent accent-[#c2fa69]"
              />
              <span className="text-sm" style={{ color: '#d1d5db' }}>
                I have read and agree to the <strong className="text-white">Terms of Service</strong> (v{LEGAL_VERSIONS.terms})
              </span>
            </label>
            <label className="flex items-start gap-3 cursor-pointer group">
              <input
                type="checkbox"
                checked={privacyAccepted}
                onChange={(e) => setPrivacyAccepted(e.target.checked)}
                className="mt-0.5 h-4 w-4 rounded border-white/20 bg-transparent accent-[#c2fa69]"
              />
              <span className="text-sm" style={{ color: '#d1d5db' }}>
                I have read and agree to the <strong className="text-white">Privacy Policy</strong> (v{LEGAL_VERSIONS.privacy})
              </span>
            </label>
          </div>

          {/* Error */}
          {error && (
            <p className="text-sm text-red-400">{error}</p>
          )}

          {/* Accept Button */}
          <button
            onClick={handleAccept}
            disabled={!canProceed || loading}
            className="w-full rounded-lg py-3 text-sm font-bold transition-all disabled:opacity-40 disabled:cursor-not-allowed"
            style={{
              background: canProceed ? '#c2fa69' : '#c2fa6940',
              color: '#0a0a0a',
            }}
          >
            {loading ? 'Recording your acceptance\u2026' : 'I Accept & Continue'}
          </button>

          {/* Footer note */}
          <div className="text-center space-y-1">
            <p className="text-[11px]" style={{ color: '#6b7280' }}>
              Your acceptance is recorded with timestamp and IP address.
            </p>
            <p className="text-[11px]" style={{ color: '#6b7280' }}>
              Version {LEGAL_VERSIONS.terms} &mdash; Effective {LEGAL_EFFECTIVE_DATE}
            </p>
            <p className="text-[11px]" style={{ color: '#4b5563' }}>
              Questions? Contact legal@aisentinels.io
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
