/**
 * Drizzle database client factory.
 *
 * Two connection modes:
 *  1. IAM auth (prod/staging) — token generated by @aws-sdk/rds-signer,
 *     used as password when connecting to RDS Proxy.
 *  2. URL auth (dev/CI) — DATABASE_URL env var with plaintext password.
 *
 * Usage:
 *   import { createDb } from '@aisentinels/db';
 *   const { db, sql } = await createDb();
 *   await db.select().from(tenants);
 */
import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import { Signer } from '@aws-sdk/rds-signer';
import * as schema from './schema/index.ts';

export type Db = ReturnType<typeof drizzle<typeof schema>>;

export interface DbConfig {
  /** RDS Proxy hostname (from SSM /aisentinels/{env}/data/aurora-proxy-endpoint) */
  host?: string;
  port?: number;
  database?: string;
  username?: string;
  region?: string;
  /** Set to true to use IAM auth instead of password */
  iamAuth?: boolean;
  /** Direct connection URL — overrides all above (dev / local use only) */
  url?: string;
  /** Connection pool max size (default 10) */
  maxConnections?: number;
}

/**
 * Creates a Drizzle db instance.
 * Must be called in an async context (IAM token fetch is async).
 */
export async function createDb(config?: DbConfig): Promise<{ db: Db; client: postgres.Sql }> {
  const maxConnections = config?.maxConnections ?? 10;

  let connectionString: string;

  if (config?.url) {
    // Dev / local — plaintext DATABASE_URL
    connectionString = config.url;
  } else if (config?.iamAuth) {
    // Prod — RDS Proxy IAM auth token
    const host = config.host ?? mustEnv('AURORA_PROXY_ENDPOINT');
    const port = config.port ?? 5432;
    const username = config.username ?? mustEnv('AURORA_DB_USER');
    const region = config.region ?? (process.env.AWS_DEFAULT_REGION ?? 'us-east-1');
    const database = config.database ?? 'aisentinels';

    const signer = new Signer({ hostname: host, port, username, region });
    const token = await signer.getAuthToken();

    connectionString =
      `postgresql://${username}:${encodeURIComponent(token)}@${host}:${port}/${database}` +
      `?sslmode=require`;
  } else {
    // Fallback — DATABASE_URL environment variable
    connectionString = mustEnv('DATABASE_URL');
  }

  const client = postgres(connectionString, {
    max: maxConnections,
    // IAM tokens expire after 15 minutes — rotate on new connections
    idle_timeout: 60,
    connect_timeout: 10,
    ssl: connectionString.includes('sslmode=require') ? 'require' : undefined,
  });

  const db = drizzle(client, { schema, logger: process.env.NODE_ENV !== 'production' });

  return { db, client };
}

/**
 * Singleton for Lambda / Fargate tasks — call once per process.
 * Lazily initialises on first access.
 */
let _singleton: { db: Db; client: postgres.Sql } | null = null;

export async function getDb(): Promise<Db> {
  if (!_singleton) {
    const isIam = process.env.AURORA_IAM_AUTH === 'true';
    _singleton = await createDb(
      isIam
        ? { iamAuth: true }
        : { url: process.env.DATABASE_URL ?? 'postgresql://localhost:5432/aisentinels' },
    );
  }
  return _singleton.db;
}

function mustEnv(key: string): string {
  const value = process.env[key];
  if (!value) throw new Error(`Required environment variable ${key} is not set`);
  return value;
}
