/**
 * Board Report PDF Renderer — Phase 9-A
 *
 * Uses puppeteer-core + @sparticuz/chromium for Lambda-compatible
 * HTML-to-PDF rendering. Generates A4 board-quality PDF with:
 *   - Header: shield logo, brand, period
 *   - Executive Summary
 *   - Compliance Scores (per standard)
 *   - CAPA Status + overdue items table
 *   - Audit Findings Trend (3-month table)
 *   - Document Completion (horizontal bar)
 *   - Sentinel Activity (table)
 *   - Footer: confidential notice, page number
 *
 * All styles are inline CSS — no external dependencies.
 */
import chromium from '@sparticuz/chromium';
import puppeteer from 'puppeteer-core';
import type { BoardReportData } from '../types/board-report.ts';

// ── Main render function ─────────────────────────────────────────────────────

export async function renderBoardReportPDF(data: BoardReportData): Promise<Buffer> {
  const html = buildHTML(data);

  const browser = await puppeteer.launch({
    executablePath: await chromium.executablePath(),
    args: chromium.args,
    headless: true,
    defaultViewport: { width: 1200, height: 800 },
  });

  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });

    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: '40px', right: '40px', bottom: '60px', left: '40px' },
      displayHeaderFooter: true,
      headerTemplate: '<span></span>',
      footerTemplate: `
        <div style="width:100%;font-size:8px;color:#999;padding:0 40px;display:flex;justify-content:space-between;">
          <span>Confidential — AI Sentinels IMS Board Report ${data.reportPeriod.label}</span>
          <span>Generated by Omni · AI Sentinels Virtual Quality Manager</span>
          <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
        </div>
      `,
    });

    return Buffer.from(pdfBuffer);
  } finally {
    await browser.close();
  }
}

// ── HTML builder ─────────────────────────────────────────────────────────────

function buildHTML(data: BoardReportData): string {
  const generatedDate = new Date(data.generatedAt).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: system-ui, -apple-system, 'Segoe UI', sans-serif;
    color: #1a1a2e;
    font-size: 11px;
    line-height: 1.5;
    background: white;
  }
  .page { padding: 0; }
  .header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    padding-bottom: 16px;
    border-bottom: 2px solid #1a1a2e;
    margin-bottom: 24px;
  }
  .header-left { display: flex; align-items: center; gap: 12px; }
  .shield {
    width: 40px; height: 40px;
    background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
    border: 1.5px solid rgba(0,0,0,0.15);
    border-radius: 8px;
    display: flex; align-items: center; justify-content: center;
  }
  .brand-name { font-size: 16px; font-weight: 700; color: #1a1a2e; }
  .brand-sub { font-size: 9px; color: #666; letter-spacing: 0.08em; font-family: monospace; }
  .header-right { text-align: right; }
  .report-title { font-size: 10px; font-weight: 700; color: #1a1a2e; letter-spacing: 0.1em; text-transform: uppercase; }
  .report-period { font-size: 14px; color: #666; margin-top: 2px; }
  .report-date { font-size: 9px; color: #999; margin-top: 2px; }

  .section { margin-bottom: 20px; }
  .section-title {
    font-size: 12px; font-weight: 700; color: #1a1a2e;
    border-bottom: 1px solid #e5e7eb;
    padding-bottom: 4px;
    margin-bottom: 12px;
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }

  .exec-summary {
    background: #f8f9fa;
    border-left: 3px solid #1a1a2e;
    padding: 14px 16px;
    font-style: italic;
    font-size: 10.5px;
    line-height: 1.6;
    color: #333;
    white-space: pre-line;
  }

  .cards-row { display: flex; gap: 12px; }
  .score-card {
    flex: 1;
    border: 1px solid #e5e7eb;
    border-radius: 8px;
    padding: 12px;
    text-align: center;
  }
  .score-card .standard-name { font-size: 10px; font-weight: 600; color: #666; margin-bottom: 4px; }
  .score-card .score-num { font-size: 28px; font-weight: 800; margin: 4px 0; }
  .score-green { color: #16a34a; }
  .score-amber { color: #d97706; }
  .score-red { color: #dc2626; }
  .progress-bar {
    height: 6px; background: #e5e7eb; border-radius: 3px;
    overflow: hidden; margin: 6px 0;
  }
  .progress-fill { height: 100%; border-radius: 3px; }
  .fill-green { background: #16a34a; }
  .fill-amber { background: #d97706; }
  .fill-red { background: #dc2626; }
  .score-meta { font-size: 9px; color: #999; }
  .trend-arrow { font-size: 12px; }

  .capa-summary { display: flex; gap: 16px; margin-bottom: 10px; }
  .capa-stat { text-align: center; }
  .capa-stat .stat-val { font-size: 20px; font-weight: 700; }
  .capa-stat .stat-label { font-size: 9px; color: #666; }
  .overdue-val { color: #dc2626; }

  table { width: 100%; border-collapse: collapse; font-size: 10px; }
  th { background: #f3f4f6; font-weight: 600; text-align: left; padding: 6px 8px; border: 1px solid #e5e7eb; }
  td { padding: 6px 8px; border: 1px solid #e5e7eb; }
  .critical-row { background: #fef2f2; }

  .doc-bar-container { margin: 8px 0; }
  .doc-bar {
    display: flex; height: 24px; border-radius: 4px; overflow: hidden;
    background: #e5e7eb;
  }
  .doc-approved { background: #16a34a; }
  .doc-pending { background: #d97706; }
  .doc-draft { background: #9ca3af; }
  .doc-bar-label { display: flex; gap: 16px; margin-top: 4px; font-size: 9px; }
  .legend-dot { display: inline-block; width: 8px; height: 8px; border-radius: 50%; margin-right: 4px; vertical-align: middle; }

  .sentinel-dot { display: inline-block; width: 10px; height: 10px; border-radius: 50%; margin-right: 6px; vertical-align: middle; }
</style>
</head>
<body>
<div class="page">

  <!-- HEADER -->
  <div class="header">
    <div class="header-left">
      <div class="shield">
        <svg width="20" height="23" viewBox="0 0 28 32" fill="none">
          <path d="M14 0L28 6V16C28 23.732 21.732 30.928 14 32C6.268 30.928 0 23.732 0 16V6L14 0Z"
                fill="rgba(255,255,255,0.3)" stroke="rgba(255,255,255,0.6)" stroke-width="1"/>
          <text x="14" y="22" text-anchor="middle" fill="white" font-size="13" font-weight="700"
                font-family="system-ui, sans-serif">S</text>
        </svg>
      </div>
      <div>
        <div class="brand-name">AI Sentinels</div>
        <div class="brand-sub">INTEGRATED MANAGEMENT SYSTEM</div>
      </div>
    </div>
    <div class="header-right">
      <div class="report-title">Board Performance Report</div>
      <div class="report-period">${data.reportPeriod.label}</div>
      <div class="report-date">Generated ${generatedDate}</div>
    </div>
  </div>

  <!-- SECTION 1: Executive Summary -->
  <div class="section">
    <div class="section-title">Executive Summary</div>
    <div class="exec-summary">${escapeHtml(data.executiveSummary)}</div>
  </div>

  <!-- SECTION 2: Compliance Scores -->
  <div class="section">
    <div class="section-title">Compliance Scores</div>
    <div class="cards-row">
      ${data.complianceScores.byStandard.map((s) => {
        const cls = s.score >= 80 ? 'green' : s.score >= 60 ? 'amber' : 'red';
        const arrow = s.trend === 'up' ? '&#x2191;' : s.trend === 'down' ? '&#x2193;' : '&#x2192;';
        return `
      <div class="score-card">
        <div class="standard-name">${escapeHtml(s.standard)}</div>
        <div class="score-num score-${cls}">${s.score}%</div>
        <div class="progress-bar"><div class="progress-fill fill-${cls}" style="width:${s.score}%"></div></div>
        <div class="score-meta">${s.activeControls} of ${s.totalControls} controls active <span class="trend-arrow">${arrow}</span></div>
      </div>`;
      }).join('')}
    </div>
  </div>

  <!-- SECTION 3: CAPA Status -->
  <div class="section">
    <div class="section-title">CAPA Status</div>
    <div class="capa-summary">
      <div class="capa-stat"><div class="stat-val">${data.capasSummary.total}</div><div class="stat-label">Total</div></div>
      <div class="capa-stat"><div class="stat-val">${data.capasSummary.open}</div><div class="stat-label">Open</div></div>
      <div class="capa-stat"><div class="stat-val">${data.capasSummary.inProgress}</div><div class="stat-label">In Progress</div></div>
      <div class="capa-stat"><div class="stat-val ${data.capasSummary.overdue > 0 ? 'overdue-val' : ''}">${data.capasSummary.overdue}</div><div class="stat-label">Overdue</div></div>
      <div class="capa-stat"><div class="stat-val" style="color:#16a34a">${data.capasSummary.closedThisPeriod}</div><div class="stat-label">Closed This Period</div></div>
    </div>
    ${data.capasSummary.overdueItems.length > 0 ? `
    <table>
      <thead><tr><th>Title</th><th>Days Overdue</th><th>Severity</th></tr></thead>
      <tbody>
        ${data.capasSummary.overdueItems.map((item) => `
        <tr class="${item.severity === 'critical' ? 'critical-row' : ''}">
          <td>${escapeHtml(item.title)}</td>
          <td style="color:#dc2626;font-weight:600">${item.daysOverdue}</td>
          <td>${escapeHtml(item.severity)}</td>
        </tr>`).join('')}
      </tbody>
    </table>` : '<div style="color:#16a34a;font-size:10px;">No overdue corrective actions. Well done.</div>'}
  </div>

  <!-- SECTION 4: Audit Findings Trend -->
  <div class="section">
    <div class="section-title">Audit Findings Trend</div>
    ${data.auditFindings.trend.length > 0 ? `
    <table>
      <thead><tr><th>Month</th><th>Major</th><th>Minor</th><th>Observations</th><th>Total</th></tr></thead>
      <tbody>
        ${data.auditFindings.trend.map((t) => `
        <tr>
          <td>${escapeHtml(t.month)}</td>
          <td style="${t.major > 0 ? 'color:#dc2626;font-weight:600' : ''}">${t.major}</td>
          <td>${t.minor}</td>
          <td>${t.observations}</td>
          <td style="font-weight:600">${t.major + t.minor + t.observations}</td>
        </tr>`).join('')}
      </tbody>
    </table>` : '<div style="color:#999;font-size:10px;">No audit findings recorded in the last 3 months.</div>'}
    <div style="margin-top:6px;font-size:10px;color:#666;">${data.auditFindings.closureRate}% of findings closed this period</div>
  </div>

  <!-- SECTION 5: Document Completion -->
  <div class="section">
    <div class="section-title">Document Completion</div>
    <div class="doc-bar-container">
      <div class="doc-bar">
        ${data.documentCompletion.total > 0 ? `
        <div class="doc-approved" style="width:${(data.documentCompletion.approved / data.documentCompletion.total) * 100}%"></div>
        <div class="doc-pending" style="width:${(data.documentCompletion.pendingApproval / data.documentCompletion.total) * 100}%"></div>
        <div class="doc-draft" style="width:${(data.documentCompletion.draft / data.documentCompletion.total) * 100}%"></div>
        ` : ''}
      </div>
      <div class="doc-bar-label">
        <span><span class="legend-dot" style="background:#16a34a"></span>Approved (${data.documentCompletion.approved})</span>
        <span><span class="legend-dot" style="background:#d97706"></span>Pending (${data.documentCompletion.pendingApproval})</span>
        <span><span class="legend-dot" style="background:#9ca3af"></span>Draft (${data.documentCompletion.draft})</span>
      </div>
    </div>
    <div style="font-size:10px;color:#666;">${data.documentCompletion.approved} of ${data.documentCompletion.total} documents approved (${data.documentCompletion.completionRate}%)</div>
  </div>

  <!-- SECTION 6: Sentinel Activity -->
  <div class="section">
    <div class="section-title">Sentinel Activity</div>
    ${data.sentinelActivity.bySentinel.length > 0 ? `
    <table>
      <thead><tr><th>Sentinel</th><th>Interactions</th><th>Top Action</th></tr></thead>
      <tbody>
        ${data.sentinelActivity.bySentinel.map((s) => `
        <tr>
          <td><span class="sentinel-dot" style="background:${s.color}"></span>${escapeHtml(s.name)}</td>
          <td>${s.interactions}</td>
          <td>${escapeHtml(s.topAction)}</td>
        </tr>`).join('')}
      </tbody>
    </table>
    <div style="margin-top:6px;font-size:10px;color:#666;">Most active sentinel: <strong>${escapeHtml(data.sentinelActivity.mostActive)}</strong> with ${data.sentinelActivity.totalInteractions} total interactions</div>
    ` : '<div style="color:#999;font-size:10px;">No sentinel activity recorded this period.</div>'}
  </div>

</div>
</body>
</html>`;
}

// ── HTML escaper ─────────────────────────────────────────────────────────────

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
