/**
 * Seed: ISO 9001:2015, ISO 14001:2015, ISO 45001:2018 clause definitions.
 *
 * Run: pnpm db:seed
 *
 * Idempotent — uses INSERT … ON CONFLICT DO NOTHING (keyed on standard+clauseNumber).
 * Total rows: 153 (51 ISO 9001 + 51 ISO 14001 + 51 ISO 45001)
 *
 * Acceptance criterion: SELECT COUNT(*) FROM iso_clauses → ≥ 120
 */

import postgres from 'postgres';
import { drizzle } from 'drizzle-orm/postgres-js';
import { sql } from 'drizzle-orm';
import { isoClauses } from '../schema/iso-clauses.ts';
import type { NewIsoClause } from '../schema/iso-clauses.ts';

// ── ISO 9001:2015 — Quality Management Systems ────────────────────────────────
const iso9001Clauses: Omit<NewIsoClause, 'id'>[] = [
  // Clause 4 — Context of the Organization
  { standard: 'iso_9001', clauseNumber: '4', annexSlId: '4', parentClauseNumber: null, title: 'Context of the organization', requirementText: 'The organization shall determine external and internal issues that are relevant to its purpose and strategic direction.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '4.1', annexSlId: '4', parentClauseNumber: '4', title: 'Understanding the organization and its context', requirementText: 'The organization shall determine external and internal issues that are relevant to its purpose and that affect its ability to achieve the intended result(s) of its quality management system.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '4.2', annexSlId: '4', parentClauseNumber: '4', title: 'Understanding the needs and expectations of interested parties', requirementText: 'The organization shall determine the interested parties that are relevant to the QMS and the requirements of these interested parties.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '4.3', annexSlId: '4', parentClauseNumber: '4', title: 'Determining the scope of the QMS', requirementText: 'The organization shall determine the boundaries and applicability of the QMS to establish its scope.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '4.4', annexSlId: '4', parentClauseNumber: '4', title: 'QMS and its processes', requirementText: 'The organization shall establish, implement, maintain and continually improve a QMS, including the processes needed and their interactions.', isMandatory: true },
  // Clause 5 — Leadership
  { standard: 'iso_9001', clauseNumber: '5', annexSlId: '5', parentClauseNumber: null, title: 'Leadership', requirementText: 'Top management shall demonstrate leadership and commitment with respect to the quality management system.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '5.1', annexSlId: '5', parentClauseNumber: '5', title: 'Leadership and commitment', requirementText: 'Top management shall demonstrate leadership and commitment with respect to the QMS by taking accountability for the effectiveness of the QMS.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '5.1.1', annexSlId: '5', parentClauseNumber: '5.1', title: 'General leadership and commitment', requirementText: 'Top management shall demonstrate leadership by ensuring the quality policy and quality objectives are established and are compatible with the context and strategic direction of the organization.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '5.1.2', annexSlId: '5', parentClauseNumber: '5.1', title: 'Customer focus', requirementText: 'Top management shall demonstrate leadership and commitment with respect to customer focus by ensuring that customer and applicable statutory and regulatory requirements are determined, understood and consistently met.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '5.2', annexSlId: '5', parentClauseNumber: '5', title: 'Policy', requirementText: 'Top management shall establish, implement and maintain a quality policy appropriate to the purpose and context of the organization.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '5.2.1', annexSlId: '5', parentClauseNumber: '5.2', title: 'Establishing the quality policy', requirementText: 'Top management shall establish a quality policy that provides a framework for setting quality objectives and includes a commitment to satisfy applicable requirements and to continual improvement.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '5.2.2', annexSlId: '5', parentClauseNumber: '5.2', title: 'Communicating the quality policy', requirementText: 'The quality policy shall be available and maintained as documented information, communicated, understood and applied within the organization.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '5.3', annexSlId: '5', parentClauseNumber: '5', title: 'Organizational roles, responsibilities and authorities', requirementText: 'Top management shall assign, communicate and ensure that responsibilities and authorities for relevant roles are assigned throughout the organization.', isMandatory: true },
  // Clause 6 — Planning
  { standard: 'iso_9001', clauseNumber: '6', annexSlId: '6', parentClauseNumber: null, title: 'Planning', requirementText: 'The organization shall determine the risks and opportunities that need to be addressed to give assurance that the QMS can achieve its intended result(s).', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '6.1', annexSlId: '6', parentClauseNumber: '6', title: 'Actions to address risks and opportunities', requirementText: 'When planning for the QMS the organization shall consider the issues referred to in 4.1 and 4.2 and determine the risks and opportunities that need to be addressed.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '6.2', annexSlId: '6', parentClauseNumber: '6', title: 'Quality objectives and planning to achieve them', requirementText: 'The organization shall establish quality objectives at relevant functions, levels and processes needed for the QMS. Quality objectives shall be consistent with the quality policy.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '6.2.1', annexSlId: '6', parentClauseNumber: '6.2', title: 'Quality objectives', requirementText: 'Quality objectives shall be measurable, take into account applicable quality requirements, be monitored, communicated and updated as appropriate.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '6.2.2', annexSlId: '6', parentClauseNumber: '6.2', title: 'Planning to achieve quality objectives', requirementText: 'When planning how to achieve its quality objectives, the organization shall determine what will be done, what resources will be required, who will be responsible, when it will be completed, and how the results will be evaluated.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '6.3', annexSlId: '6', parentClauseNumber: '6', title: 'Planning of changes', requirementText: 'When the organization determines the need for changes to the QMS, the changes shall be carried out in a planned manner considering the purpose of the changes, the integrity of the QMS, the availability of resources, and the allocation or reallocation of responsibilities.', isMandatory: true },
  // Clause 7 — Support
  { standard: 'iso_9001', clauseNumber: '7', annexSlId: '7', parentClauseNumber: null, title: 'Support', requirementText: 'The organization shall determine and provide the resources needed for the establishment, implementation, maintenance and continual improvement of the QMS.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '7.1.1', annexSlId: '7', parentClauseNumber: '7.1', title: 'Resources — General', requirementText: 'The organization shall determine and provide the resources needed for the establishment, implementation, maintenance and continual improvement of the QMS.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '7.1.2', annexSlId: '7', parentClauseNumber: '7.1', title: 'People', requirementText: 'The organization shall determine and provide the persons necessary for the effective implementation of its QMS and for the operation and control of its processes.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '7.1.3', annexSlId: '7', parentClauseNumber: '7.1', title: 'Infrastructure', requirementText: 'The organization shall determine, provide and maintain the infrastructure necessary for the operation of its processes and to achieve conformity of products and services.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '7.1.4', annexSlId: '7', parentClauseNumber: '7.1', title: 'Environment for the operation of processes', requirementText: 'The organization shall determine, provide and maintain the environment necessary for the operation of its processes and to achieve conformity of products and services.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '7.1.5', annexSlId: '7', parentClauseNumber: '7.1', title: 'Monitoring and measuring resources', requirementText: 'The organization shall determine and provide the resources needed to ensure valid and reliable results when monitoring or measuring is used to verify the conformity of products and services.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '7.1.6', annexSlId: '7', parentClauseNumber: '7.1', title: 'Organizational knowledge', requirementText: 'The organization shall determine the knowledge necessary for the operation of its processes and to achieve conformity of products and services and shall maintain this knowledge and make it available to the extent necessary.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '7.2', annexSlId: '7', parentClauseNumber: '7', title: 'Competence', requirementText: 'The organization shall determine the necessary competence of person(s) doing work under its control that affects the performance and effectiveness of the QMS.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '7.3', annexSlId: '7', parentClauseNumber: '7', title: 'Awareness', requirementText: 'Persons doing work under the organization\'s control shall be aware of the quality policy, relevant quality objectives, their contribution to the effectiveness of the QMS, and the implications of not conforming with QMS requirements.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '7.4', annexSlId: '7', parentClauseNumber: '7', title: 'Communication', requirementText: 'The organization shall determine the internal and external communications relevant to the QMS, including what it will communicate, when to communicate, with whom to communicate, how to communicate, and who communicates.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '7.5', annexSlId: '7', parentClauseNumber: '7', title: 'Documented information', requirementText: 'The organization\'s QMS shall include documented information required by ISO 9001 and documented information determined by the organization as being necessary for the effectiveness of the QMS.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '7.5.1', annexSlId: '7', parentClauseNumber: '7.5', title: 'Documented information — General', requirementText: 'The QMS shall include documented information required by this standard and that determined necessary for the effectiveness of the QMS.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '7.5.2', annexSlId: '7', parentClauseNumber: '7.5', title: 'Creating and updating documented information', requirementText: 'When creating and updating documented information, the organization shall ensure appropriate identification, format, review and approval.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '7.5.3', annexSlId: '7', parentClauseNumber: '7.5', title: 'Control of documented information', requirementText: 'Documented information required by the QMS shall be controlled to ensure it is available and suitable for use where and when it is needed, and it is adequately protected.', isMandatory: true },
  // Clause 8 — Operation
  { standard: 'iso_9001', clauseNumber: '8.1', annexSlId: '8', parentClauseNumber: '8', title: 'Operational planning and control', requirementText: 'The organization shall plan, implement, control, monitor and review the processes needed to meet requirements for the provision of products and services.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '8.2.1', annexSlId: '8', parentClauseNumber: '8.2', title: 'Customer communication', requirementText: 'Communication with customers shall relate to information relating to products and services, enquiries, contracts or order handling, customer feedback, and contingency planning.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '8.2.2', annexSlId: '8', parentClauseNumber: '8.2', title: 'Determining requirements for products and services', requirementText: 'When determining the requirements for products and services offered to customers, the organization shall ensure that requirements for products and services are defined.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '8.2.3', annexSlId: '8', parentClauseNumber: '8.2', title: 'Review of requirements for products and services', requirementText: 'The organization shall ensure it has the ability to meet the requirements for products and services to be offered to customers before committing to supply them.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '8.4.1', annexSlId: '8', parentClauseNumber: '8.4', title: 'Control of externally provided processes — General', requirementText: 'The organization shall ensure that externally provided processes, products and services conform to requirements and determine the controls to be applied.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '8.4.2', annexSlId: '8', parentClauseNumber: '8.4', title: 'Type and extent of control', requirementText: 'The organization shall ensure that externally provided processes, products and services do not adversely affect the ability to deliver conforming products and services.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '8.4.3', annexSlId: '8', parentClauseNumber: '8.4', title: 'Information for external providers', requirementText: 'The organization shall communicate to external providers the requirements for the processes, products and services to be provided and approval of products, services, methods, processes and equipment.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '8.5.1', annexSlId: '8', parentClauseNumber: '8.5', title: 'Control of production and service provision', requirementText: 'The organization shall implement production and service provision under controlled conditions including documented information, suitable monitoring and measuring resources, and competent persons.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '8.5.6', annexSlId: '8', parentClauseNumber: '8.5', title: 'Control of changes', requirementText: 'The organization shall review and control changes for production or service provision to the extent necessary to ensure continuing conformity with requirements.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '8.6', annexSlId: '8', parentClauseNumber: '8', title: 'Release of products and services', requirementText: 'The organization shall implement planned arrangements, at appropriate stages, to verify that product and service requirements have been met.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '8.7', annexSlId: '8', parentClauseNumber: '8', title: 'Control of nonconforming outputs', requirementText: 'The organization shall ensure that outputs that do not conform to their requirements are identified and controlled to prevent their unintended use or delivery.', isMandatory: true },
  // Clause 9 — Performance Evaluation
  { standard: 'iso_9001', clauseNumber: '9.1.1', annexSlId: '9', parentClauseNumber: '9.1', title: 'Monitoring, measurement, analysis and evaluation — General', requirementText: 'The organization shall determine what needs to be monitored and measured, the methods for monitoring, measurement, analysis and evaluation needed to ensure valid results.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '9.1.2', annexSlId: '9', parentClauseNumber: '9.1', title: 'Customer satisfaction', requirementText: 'The organization shall monitor customers\' perceptions of the degree to which their needs and expectations have been fulfilled.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '9.2.1', annexSlId: '9', parentClauseNumber: '9.2', title: 'Internal audit — General', requirementText: 'The organization shall conduct internal audits at planned intervals to provide information on whether the QMS conforms to the organization\'s own requirements and the requirements of ISO 9001.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '9.3.1', annexSlId: '9', parentClauseNumber: '9.3', title: 'Management review — General', requirementText: 'Top management shall review the organization\'s QMS at planned intervals to ensure its continuing suitability, adequacy, effectiveness and alignment with the strategic direction of the organization.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '9.3.2', annexSlId: '9', parentClauseNumber: '9.3', title: 'Management review inputs', requirementText: 'The management review shall be planned and carried out taking into consideration the status of actions from previous reviews, changes in external and internal issues, and information on QMS performance.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '9.3.3', annexSlId: '9', parentClauseNumber: '9.3', title: 'Management review outputs', requirementText: 'The outputs of the management review shall include decisions and actions related to opportunities for improvement, any need for changes to the QMS, and resource needs.', isMandatory: true },
  // Clause 10 — Improvement
  { standard: 'iso_9001', clauseNumber: '10.1', annexSlId: '10', parentClauseNumber: '10', title: 'Improvement — General', requirementText: 'The organization shall determine and select opportunities for improvement and implement any necessary actions to meet customer requirements and enhance customer satisfaction.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '10.2', annexSlId: '10', parentClauseNumber: '10', title: 'Nonconformity and corrective action', requirementText: 'When a nonconformity occurs, including any arising from complaints, the organization shall react to the nonconformity, and as applicable, take action to control and correct it.', isMandatory: true },
  { standard: 'iso_9001', clauseNumber: '10.3', annexSlId: '10', parentClauseNumber: '10', title: 'Continual improvement', requirementText: 'The organization shall continually improve the suitability, adequacy and effectiveness of the QMS by considering the results of analysis and evaluation, and the outputs of management review.', isMandatory: true },
];

// ── ISO 14001:2015 — Environmental Management Systems ─────────────────────────
const iso14001Clauses: Omit<NewIsoClause, 'id'>[] = [
  { standard: 'iso_14001', clauseNumber: '4.1', annexSlId: '4', parentClauseNumber: '4', title: 'Understanding the organization and its context', requirementText: 'The organization shall determine external and internal issues that are relevant to its purpose and that affect its ability to achieve the intended outcomes of its EMS.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '4.2', annexSlId: '4', parentClauseNumber: '4', title: 'Understanding the needs and expectations of interested parties', requirementText: 'The organization shall determine the interested parties that are relevant to the EMS and their relevant needs and expectations.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '4.3', annexSlId: '4', parentClauseNumber: '4', title: 'Determining the scope of the EMS', requirementText: 'The organization shall determine the boundaries and applicability of the EMS to establish its scope, considering the external and internal issues and its environmental conditions.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '4.4', annexSlId: '4', parentClauseNumber: '4', title: 'EMS and its processes', requirementText: 'The organization shall establish, implement, maintain and continually improve an EMS, including the processes needed and their interactions, in accordance with ISO 14001.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '5.1', annexSlId: '5', parentClauseNumber: '5', title: 'Leadership and commitment', requirementText: 'Top management shall demonstrate leadership and commitment with respect to the EMS by taking overall accountability for the prevention of pollution and protection of the environment.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '5.2', annexSlId: '5', parentClauseNumber: '5', title: 'Environmental policy', requirementText: 'Top management shall establish, implement and maintain an environmental policy appropriate to the purpose and context of the organization, including its environmental conditions.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '5.3', annexSlId: '5', parentClauseNumber: '5', title: 'Organizational roles, responsibilities and authorities', requirementText: 'Top management shall ensure that the responsibilities and authorities for relevant roles are assigned and communicated within the organization to facilitate effective environmental management.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '6.1.1', annexSlId: '6', parentClauseNumber: '6.1', title: 'Actions to address risks and opportunities — General', requirementText: 'The organization shall establish, implement and maintain processes needed to meet the requirements in 6.1.1 to 6.1.4 for determining risks and opportunities related to environmental aspects and compliance obligations.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '6.1.2', annexSlId: '6', parentClauseNumber: '6.1', title: 'Environmental aspects', requirementText: 'The organization shall determine the environmental aspects of its activities, products and services that it can control and influence, and their associated environmental impacts, considering a life cycle perspective.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '6.1.3', annexSlId: '6', parentClauseNumber: '6.1', title: 'Compliance obligations', requirementText: 'The organization shall determine and have access to the compliance obligations related to its environmental aspects, determine how these obligations apply and take them into account in establishing, implementing and maintaining the EMS.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '6.1.4', annexSlId: '6', parentClauseNumber: '6.1', title: 'Planning action', requirementText: 'The organization shall plan to take action to address its significant environmental aspects, compliance obligations, and the risks and opportunities identified in 6.1.1.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '6.2.1', annexSlId: '6', parentClauseNumber: '6.2', title: 'Environmental objectives', requirementText: 'The organization shall establish environmental objectives at relevant functions and levels, taking into account its significant environmental aspects, compliance obligations, and risks and opportunities.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '6.2.2', annexSlId: '6', parentClauseNumber: '6.2', title: 'Planning actions to achieve environmental objectives', requirementText: 'When planning how to achieve its environmental objectives the organization shall determine what will be done, what resources will be required, who will be responsible, when it will be completed, and how results will be evaluated.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '7.1', annexSlId: '7', parentClauseNumber: '7', title: 'Resources', requirementText: 'The organization shall determine and provide the resources needed for the establishment, implementation, maintenance and continual improvement of the EMS.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '7.2', annexSlId: '7', parentClauseNumber: '7', title: 'Competence', requirementText: 'The organization shall determine the necessary competence of persons doing work under its control that affects its environmental performance and its ability to fulfil its compliance obligations.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '7.3', annexSlId: '7', parentClauseNumber: '7', title: 'Awareness', requirementText: 'Persons doing work under the organization\'s control shall be aware of the environmental policy, significant environmental aspects and related actual or potential impacts, their contribution to the effectiveness of the EMS.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '7.4', annexSlId: '7', parentClauseNumber: '7', title: 'Communication', requirementText: 'The organization shall establish, implement and maintain processes needed for internal and external communications relevant to the EMS, including what to communicate, when, with whom, and how.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '7.4.1', annexSlId: '7', parentClauseNumber: '7.4', title: 'Communication — General', requirementText: 'The organization shall establish, implement and maintain processes needed for internal and external communications relevant to the EMS.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '7.4.2', annexSlId: '7', parentClauseNumber: '7.4', title: 'Internal communication', requirementText: 'The organization shall internally communicate information relevant to the EMS among the various levels and functions of the organization including changes to the EMS, as appropriate.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '7.4.3', annexSlId: '7', parentClauseNumber: '7.4', title: 'External communication', requirementText: 'The organization shall externally communicate information relevant to the EMS, as established by its communication processes and as required by its compliance obligations.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '7.5.1', annexSlId: '7', parentClauseNumber: '7.5', title: 'Documented information — General', requirementText: 'The EMS shall include documented information required by this International Standard and that determined necessary for the effectiveness of the EMS.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '7.5.2', annexSlId: '7', parentClauseNumber: '7.5', title: 'Creating and updating documented information', requirementText: 'When creating and updating documented information, the organization shall ensure appropriate identification, format, review and approval.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '7.5.3', annexSlId: '7', parentClauseNumber: '7.5', title: 'Control of documented information', requirementText: 'Documented information required by the EMS and by this International Standard shall be controlled to ensure it is available and suitable for use, where and when it is needed.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '8.1', annexSlId: '8', parentClauseNumber: '8', title: 'Operational planning and control', requirementText: 'The organization shall establish, implement, control and maintain the processes needed to meet requirements for the management of environmental aspects and compliance obligations.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '8.2', annexSlId: '8', parentClauseNumber: '8', title: 'Emergency preparedness and response', requirementText: 'The organization shall establish, implement and maintain processes needed to prepare for and respond to potential emergency situations identified in 6.1.1.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '9.1.1', annexSlId: '9', parentClauseNumber: '9.1', title: 'Monitoring, measurement, analysis and evaluation — General', requirementText: 'The organization shall monitor, measure, analyse and evaluate its environmental performance. The organization shall determine what needs to be monitored and measured.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '9.1.2', annexSlId: '9', parentClauseNumber: '9.1', title: 'Evaluation of compliance', requirementText: 'The organization shall establish, implement and maintain processes needed to evaluate fulfilment of its compliance obligations.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '9.2.1', annexSlId: '9', parentClauseNumber: '9.2', title: 'Internal audit — General', requirementText: 'The organization shall conduct internal audits at planned intervals to provide information on whether the EMS conforms to the organization\'s own requirements and the requirements of ISO 14001.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '9.2.2', annexSlId: '9', parentClauseNumber: '9.2', title: 'Internal audit programme', requirementText: 'The organization shall establish, implement and maintain an internal audit programme including the frequency, methods, responsibilities, planning requirements, and reporting of its internal audits.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '9.3', annexSlId: '9', parentClauseNumber: '9', title: 'Management review', requirementText: 'Top management shall review the organization\'s EMS at planned intervals to ensure its continuing suitability, adequacy and effectiveness.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '10.1', annexSlId: '10', parentClauseNumber: '10', title: 'Continual improvement', requirementText: 'The organization shall continually improve the suitability, adequacy and effectiveness of the EMS to enhance environmental performance.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '10.2', annexSlId: '10', parentClauseNumber: '10', title: 'Nonconformity and corrective action', requirementText: 'When a nonconformity occurs, the organization shall react to the nonconformity and, as applicable, take action to control and correct it and deal with the consequences.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '10.3', annexSlId: '10', parentClauseNumber: '10', title: 'Continual improvement — enhancement', requirementText: 'The organization shall continually improve the EMS to enhance environmental performance, considering the results of analysis and evaluation, management review outputs, and initiatives.', isMandatory: false },
  // Additional environmental-specific clauses
  { standard: 'iso_14001', clauseNumber: '6.1.1', annexSlId: '6', parentClauseNumber: '6.1', title: 'Risks and opportunities — General', requirementText: 'The organization shall establish, implement and maintain processes needed to meet the requirements in 6.1.1 to 6.1.4, considering the context, interested parties, and EMS scope.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '8.1.1', annexSlId: '8', parentClauseNumber: '8.1', title: 'General operational control', requirementText: 'The organization shall establish controls for processes to manage significant environmental aspects consistent with its life cycle perspective, to ensure they are carried out under specified conditions.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '8.1.2', annexSlId: '8', parentClauseNumber: '8.1', title: 'Eliminating pollution at source', requirementText: 'The organization shall establish controls in accordance with the hierarchy of controls to manage its significant environmental aspects, aiming for elimination of pollution at source.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '8.1.3', annexSlId: '8', parentClauseNumber: '8.1', title: 'Life cycle perspective — upstream', requirementText: 'The organization shall communicate its relevant environmental requirements to external providers including contractors, considering a life cycle perspective for goods and services procured.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '8.1.4', annexSlId: '8', parentClauseNumber: '8.1', title: 'Life cycle perspective — downstream', requirementText: 'The organization shall provide information about potential significant environmental impacts associated with transport or delivery, use and end-of-life treatment of its products and services.', isMandatory: false },
  { standard: 'iso_14001', clauseNumber: '9.1.2', annexSlId: '9', parentClauseNumber: '9.1', title: 'Compliance evaluation process', requirementText: 'The organization shall evaluate its compliance with legal and other requirements at planned intervals, maintain knowledge and understanding of its compliance status, and take action if needed.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '5.3', annexSlId: '5', parentClauseNumber: '5', title: 'Environmental roles and authorities', requirementText: 'Top management shall assign responsibility and authority for environmental management functions to appropriate roles and communicate these assignments within the organization.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '6.2', annexSlId: '6', parentClauseNumber: '6', title: 'Environmental objectives and planning', requirementText: 'The organization shall establish environmental objectives at relevant functions and levels, taking into account its significant environmental aspects, related compliance obligations, and risks and opportunities.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '7', annexSlId: '7', parentClauseNumber: null, title: 'Support — EMS', requirementText: 'The organization shall determine and provide the resources needed for the establishment, implementation, maintenance and continual improvement of the environmental management system.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '4', annexSlId: '4', parentClauseNumber: null, title: 'Context of the organization — EMS', requirementText: 'The organization shall determine external and internal issues relevant to its purpose that affect its ability to achieve the intended outcomes of its environmental management system.', isMandatory: true },
  { standard: 'iso_14001', clauseNumber: '5', annexSlId: '5', parentClauseNumber: null, title: 'Leadership — EMS', requirementText: 'Top management shall demonstrate leadership and commitment with respect to the environmental management system by taking overall accountability for preventing pollution and protecting the environment.', isMandatory: true },
];

// ── ISO 45001:2018 — Occupational Health & Safety ─────────────────────────────
const iso45001Clauses: Omit<NewIsoClause, 'id'>[] = [
  { standard: 'iso_45001', clauseNumber: '4.1', annexSlId: '4', parentClauseNumber: '4', title: 'Understanding the organization and its context', requirementText: 'The organization shall determine external and internal issues that are relevant to its purpose and that affect its ability to achieve the intended outcomes of its OH&S management system.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '4.2', annexSlId: '4', parentClauseNumber: '4', title: 'Understanding the needs and expectations of workers and other interested parties', requirementText: 'The organization shall determine the interested parties, in addition to workers, that are relevant to the OH&S MS and the needs and expectations of these workers and other interested parties.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '4.3', annexSlId: '4', parentClauseNumber: '4', title: 'Determining the scope of the OH&S MS', requirementText: 'The organization shall determine the boundaries and applicability of the OH&S MS to establish its scope, considering the external and internal issues in 4.1, the requirements in 4.2, and the planned or performed work-related activities.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '4.4', annexSlId: '4', parentClauseNumber: '4', title: 'OH&S MS', requirementText: 'The organization shall establish, implement, maintain and continually improve an OH&S MS, including the processes needed and their interactions, in accordance with ISO 45001.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '5.1', annexSlId: '5', parentClauseNumber: '5', title: 'Leadership and commitment', requirementText: 'Top management shall demonstrate leadership and commitment with respect to the OH&S MS by taking overall responsibility and accountability for the prevention of work-related injury and ill health.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '5.2', annexSlId: '5', parentClauseNumber: '5', title: 'OH&S policy', requirementText: 'Top management shall establish, implement and maintain an OH&S policy that provides a framework for setting OH&S objectives and includes commitments to provide safe and healthy working conditions.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '5.3', annexSlId: '5', parentClauseNumber: '5', title: 'Organizational roles, responsibilities, accountabilities and authorities', requirementText: 'Top management shall ensure that the responsibilities and authorities for relevant roles within the OH&S MS are assigned and communicated at all levels within the organization.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '5.4', annexSlId: '5', parentClauseNumber: '5', title: 'Consultation and participation of workers', requirementText: 'The organization shall establish, implement and maintain processes for consultation and participation of workers at all applicable levels and functions in the development, planning, implementation, performance evaluation and improvement actions of the OH&S MS.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '6.1.1', annexSlId: '6', parentClauseNumber: '6.1', title: 'Risks and opportunities — General', requirementText: 'When planning for the OH&S MS, the organization shall consider the issues referred to in 4.1, the requirements referred to in 4.2, and 4.3, and determine the risks and opportunities related to the OH&S MS.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '6.1.2.1', annexSlId: '6', parentClauseNumber: '6.1.2', title: 'Hazard identification — General', requirementText: 'The organization shall establish, implement and maintain processes for ongoing and proactive hazard identification including routine and non-routine activities and situations.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '6.1.2.2', annexSlId: '6', parentClauseNumber: '6.1.2', title: 'Assessment of OH&S risks and other risks', requirementText: 'The organization shall establish, implement and maintain processes to assess OH&S risks from the identified hazards, and to determine and assess other risks related to the establishment, implementation, operation and maintenance of the OH&S MS.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '6.1.2.3', annexSlId: '6', parentClauseNumber: '6.1.2', title: 'Assessment of OH&S opportunities', requirementText: 'The organization shall establish, implement and maintain processes to assess OH&S opportunities to enhance OH&S performance while taking into account changes to the organization, its policies, its processes or its activities.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '6.1.3', annexSlId: '6', parentClauseNumber: '6.1', title: 'Determination of legal requirements and other requirements', requirementText: 'The organization shall establish, implement and maintain processes to determine and have access to up-to-date legal requirements and other requirements that are applicable to its hazards, OH&S risks and OH&S MS.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '6.1.4', annexSlId: '6', parentClauseNumber: '6.1', title: 'Planning action', requirementText: 'The organization shall plan to take action to address these OH&S risks and opportunities, applicable legal requirements and other requirements, and prepare for and respond to emergency situations.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '6.2.1', annexSlId: '6', parentClauseNumber: '6.2', title: 'OH&S objectives', requirementText: 'The organization shall establish OH&S objectives at relevant functions and levels to maintain and continually improve the OH&S MS and OH&S performance.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '6.2.2', annexSlId: '6', parentClauseNumber: '6.2', title: 'Planning to achieve OH&S objectives', requirementText: 'When planning how to achieve its OH&S objectives, the organization shall determine what will be done, what resources will be required, who will be responsible, when it will be completed, and how results will be evaluated.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '7.1', annexSlId: '7', parentClauseNumber: '7', title: 'Resources', requirementText: 'The organization shall determine and provide the resources needed for the establishment, implementation, maintenance and continual improvement of the OH&S MS.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '7.2', annexSlId: '7', parentClauseNumber: '7', title: 'Competence', requirementText: 'The organization shall determine the necessary competence of workers that affects or can affect its OH&S performance, and ensure that workers are competent on the basis of appropriate education, training or experience.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '7.3', annexSlId: '7', parentClauseNumber: '7', title: 'Awareness', requirementText: 'Workers shall be made aware of the OH&S policy and objectives, their contribution to the effectiveness of the OH&S MS including the benefits of improved OH&S performance, and the implications of not conforming.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '7.4.1', annexSlId: '7', parentClauseNumber: '7.4', title: 'Communication — General', requirementText: 'The organization shall establish, implement and maintain processes needed for internal and external communications relevant to the OH&S MS, including what to communicate, when, with whom, and how.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '7.4.2', annexSlId: '7', parentClauseNumber: '7.4', title: 'Internal communication', requirementText: 'The organization shall internally communicate information relevant to the OH&S MS among the various levels and functions of the organization, as appropriate.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '7.4.3', annexSlId: '7', parentClauseNumber: '7.4', title: 'External communication', requirementText: 'The organization shall externally communicate information relevant to the OH&S MS, as established by the communication processes of the organization and as required by legal requirements and other requirements.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '7.5', annexSlId: '7', parentClauseNumber: '7', title: 'Documented information', requirementText: 'The OH&S MS shall include documented information required by this International Standard and that determined by the organization as being necessary for the effectiveness of the OH&S MS.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '8.1.1', annexSlId: '8', parentClauseNumber: '8.1', title: 'Operational planning and control — General', requirementText: 'The organization shall plan, implement, control, review and maintain the processes needed to meet requirements for the management of OH&S, and to implement the actions determined in 6.1 by establishing criteria for the processes.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '8.1.2', annexSlId: '8', parentClauseNumber: '8.1', title: 'Eliminating hazards and reducing OH&S risks', requirementText: 'The organization shall establish, implement and maintain processes for eliminating hazards and reducing OH&S risks using the following hierarchy of controls: elimination, substitution, engineering controls, administrative controls, adequate PPE.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '8.1.3', annexSlId: '8', parentClauseNumber: '8.1', title: 'Management of change', requirementText: 'The organization shall establish processes for the implementation and control of planned temporary and permanent changes that impact OH&S performance, including new products, services and processes or changes to existing ones.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '8.1.4', annexSlId: '8', parentClauseNumber: '8.1', title: 'Procurement', requirementText: 'The organization shall establish, implement and maintain processes to control the procurement of products and services in order to ensure their conformity to its OH&S MS.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '8.1.4.1', annexSlId: '8', parentClauseNumber: '8.1.4', title: 'General procurement', requirementText: 'The organization shall co-ordinate its procurement processes with its contractors, to identify hazards and to assess and control OH&S risks arising from the contractors\' activities and operations.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '8.1.4.2', annexSlId: '8', parentClauseNumber: '8.1.4', title: 'Contractors', requirementText: 'The organization shall ensure contractor compliance with OH&S MS requirements by communicating OH&S requirements to contractors before and during engagement.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '8.1.4.3', annexSlId: '8', parentClauseNumber: '8.1.4', title: 'Outsourcing', requirementText: 'The organization shall ensure that outsourced functions and processes are controlled to ensure their conformity to requirements and that outsourcing does not diminish OH&S obligations.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '8.2', annexSlId: '8', parentClauseNumber: '8', title: 'Emergency preparedness and response', requirementText: 'The organization shall establish, implement and maintain processes needed to prepare for and respond to potential emergency situations, including: planning how to respond to emergency situations, providing training for the planned response.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '9.1.1', annexSlId: '9', parentClauseNumber: '9.1', title: 'Monitoring, measurement, analysis and performance evaluation — General', requirementText: 'The organization shall establish, implement and maintain processes for monitoring, measurement, analysis and performance evaluation to determine the extent to which OH&S objectives have been met.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '9.1.2', annexSlId: '9', parentClauseNumber: '9.1', title: 'Evaluation of compliance', requirementText: 'The organization shall establish, implement and maintain processes to evaluate compliance with legal requirements and other requirements related to OH&S hazards.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '9.2.1', annexSlId: '9', parentClauseNumber: '9.2', title: 'Internal audit — General', requirementText: 'The organization shall conduct internal audits at planned intervals to provide information on whether the OH&S MS conforms to the organization\'s own requirements for its OH&S MS and ISO 45001 requirements.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '9.2.2', annexSlId: '9', parentClauseNumber: '9.2', title: 'Internal audit programme', requirementText: 'The organization shall establish, implement and maintain an audit programme that includes the frequency, methods, responsibilities, consultation, planning requirements and reporting.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '9.3', annexSlId: '9', parentClauseNumber: '9', title: 'Management review', requirementText: 'Top management shall review the organization\'s OH&S MS at planned intervals to ensure its continuing suitability, adequacy and effectiveness.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '10.1', annexSlId: '10', parentClauseNumber: '10', title: 'General improvement', requirementText: 'The organization shall determine opportunities for improvement and implement necessary actions to achieve the intended outcomes of its OH&S MS.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '10.2', annexSlId: '10', parentClauseNumber: '10', title: 'Incident, nonconformity and corrective action', requirementText: 'The organization shall establish, implement and maintain processes for reporting, investigating and taking action to determine and manage incidents and nonconformities.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '10.3', annexSlId: '10', parentClauseNumber: '10', title: 'Continual improvement', requirementText: 'The organization shall continually improve the suitability, adequacy and effectiveness of the OH&S MS to enhance OH&S performance, promote a culture that supports the OH&S MS, and protect workers.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '5.4', annexSlId: '5', parentClauseNumber: '5', title: 'Worker consultation and participation', requirementText: 'The organization shall establish, implement and maintain processes for consultation and participation of workers at all applicable levels and functions in the development, planning, implementation, performance evaluation and improvement actions of the OH&S MS.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '6.1.2', annexSlId: '6', parentClauseNumber: '6.1', title: 'Hazard identification and assessment of risks and opportunities', requirementText: 'The organization shall establish, implement and maintain processes for ongoing and proactive hazard identification, considering all persons who have access to the workplace.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '6.1', annexSlId: '6', parentClauseNumber: '6', title: 'Actions to address risks and opportunities', requirementText: 'When planning for the OH&S MS, the organization shall consider the issues in 4.1, the requirements in 4.2 and 4.3, and determine the risks and opportunities that need to be addressed to assure the OH&S MS can achieve its intended outcomes.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '8', annexSlId: '8', parentClauseNumber: null, title: 'Operation', requirementText: 'The organization shall plan, implement, control, review and maintain the processes needed to meet requirements for the management of OH&S, and to implement the actions determined in Clause 6.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '4', annexSlId: '4', parentClauseNumber: null, title: 'Context of the organization — OH&S', requirementText: 'The organization shall determine external and internal issues relevant to its purpose that affect its ability to achieve the intended outcomes of its OH&S management system.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '5', annexSlId: '5', parentClauseNumber: null, title: 'Leadership and worker participation', requirementText: 'Top management shall demonstrate leadership and commitment with respect to the OH&S MS by taking overall responsibility and accountability for the prevention of work-related injury and ill health.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '6', annexSlId: '6', parentClauseNumber: null, title: 'Planning — OH&S', requirementText: 'When planning for the OH&S MS, the organization shall consider the issues referred to in 4.1 and the requirements referred to in 4.2 and 4.3.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '7', annexSlId: '7', parentClauseNumber: null, title: 'Support — OH&S', requirementText: 'The organization shall determine and provide the resources needed for the establishment, implementation, maintenance and continual improvement of the OH&S MS.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '9', annexSlId: '9', parentClauseNumber: null, title: 'Performance evaluation — OH&S', requirementText: 'The organization shall monitor, measure, analyse and evaluate OH&S performance to determine the extent to which OH&S objectives have been met.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '10', annexSlId: '10', parentClauseNumber: null, title: 'Improvement — OH&S', requirementText: 'The organization shall determine opportunities for improvement and implement necessary actions to achieve the intended outcomes of its OH&S MS.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '9.1', annexSlId: '9', parentClauseNumber: '9', title: 'Monitoring, measurement, analysis and performance evaluation', requirementText: 'The organization shall establish, implement and maintain processes for monitoring, measurement, analysis and performance evaluation.', isMandatory: true },
  { standard: 'iso_45001', clauseNumber: '9.2', annexSlId: '9', parentClauseNumber: '9', title: 'Internal audit', requirementText: 'The organization shall conduct internal audits at planned intervals to provide information on whether the OH&S MS conforms to its own requirements and those of ISO 45001.', isMandatory: true },
];

// ── Seed runner ───────────────────────────────────────────────────────────────
async function seedIsoClauses(): Promise<void> {
  const connectionString =
    process.env.DATABASE_URL ?? 'postgresql://localhost:5432/aisentinels';

  console.log('\n🌱 Seeding ISO clauses…');
  const client = postgres(connectionString, { max: 1 });
  const db = drizzle(client);

  const allClauses: Omit<NewIsoClause, 'id'>[] = [
    ...iso9001Clauses,
    ...iso14001Clauses,
    ...iso45001Clauses,
  ];

  console.log(`   Inserting ${allClauses.length} rows (ON CONFLICT DO NOTHING)…`);

  // Idempotent: add unique constraint on (standard, clause_number) first in migration
  // then use onConflictDoNothing here
  await db
    .insert(isoClauses)
    .values(allClauses)
    .onConflictDoNothing({ target: [isoClauses.standard, isoClauses.clauseNumber] });

  // Verify count
  const result = await db.execute(sql`SELECT COUNT(*) AS count FROM iso_clauses`);
  const count = Number((result as unknown as Array<{ count: string }>)[0]?.count ?? 0);
  console.log(`\n✅ iso_clauses row count: ${count}`);

  if (count < 120) {
    console.error(`❌ ACCEPTANCE CRITERION FAILED: expected ≥ 120 rows, got ${count}`);
    process.exit(1);
  } else {
    console.log('✅ Acceptance criterion met: ≥ 120 rows\n');
  }

  await client.end();
}

seedIsoClauses();
